name: Build and Deploy App

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: AlexxNB/caprover-action@v1
          with:
            server: '${{ secrets.CAPROVER_SERVER }}'
            password: '${{ secrets.CAPROVER_PASSWORD }}'
            appname: 'ecs-api-license'